CONSUMPTION_DATA = "consumption_data"
PRODUCTION_DATA = "production_data"

# Default values for ConsumptionDynamics
DEFAULT_CONS_BASE_LOAD = 100.0
DEFAULT_CONS_AMPLITUDE = 50.0
DEFAULT_CONS_INTERVAL_MULTIPLIER = 1.0
DEFAULT_CONS_PERIOD_DIVISOR = 12.0
DEFAULT_CONS_PHASE_SHIFT = 0.0
DEFAULT_CONS_MORNING_PEAK = 0.1
DEFAULT_CONS_EVENING_PEAK = 0.75
DEFAULT_CONS_PEAK_CONSUMPTION1 = 100.0
DEFAULT_CONS_PEAK_TIME1 = 0.25
DEFAULT_CONS_WIDTH1 = 0.1
DEFAULT_CONS_PEAK_CONSUMPTION2 = 100.0
DEFAULT_CONS_PEAK_TIME2 = 0.75
DEFAULT_CONS_WIDTH2 = 0.1
DEFAULT_CONS_SCALE_FACTOR = 1.0
DEFAULT_CONS_PEAK_SHARPNESS = 20.0
DEFAULT_CONS_GROWTH_FACTOR = 0.5

#Default values for Production Dynamics
# Base load and amplitude
DEFAULT_PROD_BASE_LOAD = 150.0
DEFAULT_PROD_AMPLITUDE = 75.0

# Sinusoidal parameters
DEFAULT_PROD_INTERVAL_MULTIPLIER = 1.5
DEFAULT_PROD_PERIOD_DIVISOR = 10.0
DEFAULT_PROD_PHASE_SHIFT = 0.5

# Double peak parameters
DEFAULT_PROD_MORNING_PEAK = 0.2
DEFAULT_PROD_EVENING_PEAK = 0.8
DEFAULT_PROD_PEAK_SHARPNESS = 15.0

# Two-peak (linear growth) parameter
DEFAULT_PROD_GROWTH_FACTOR = 0.3

# GMM parameters
DEFAULT_PROD_PEAK1 = 150.0
DEFAULT_PROD_PEAK_TIME1 = 0.3
DEFAULT_PROD_WIDTH1 = 0.15
DEFAULT_PROD_PEAK2 = 150.0
DEFAULT_PROD_PEAK_TIME2 = 0.7
DEFAULT_PROD_WIDTH2 = 0.15

# Data-driven
DEFAULT_PROD_SCALE_FACTOR = 1.0

# Action Type Constants
ACTION_TYPE_STORAGE = "STORAGE"
ACTION_TYPE_PRODUCTION = "PRODUCTION"
ACTION_TYPE_CONSUMPTION = "CONSUMPTION"
ACTION_TYPE_TRADE = "TRADE"
