# configs/environment_config.yaml

# Time Parameters
time:
  time_steps_per_day_ratio: 1440
  step_duration: 30     # Time step duration (minutes)
  max_steps_per_episode: 48 # Steps per episode (1 days)

# Pricing Parameters
pricing:
  eta: 0.5            # Smoothing factor for running average price

# ISO Configuration Reference
iso_config_path: "configs/iso_config.yaml"

# PCSUnit Configuration Reference
pcs_unit_config_path: "configs/pcs_unit_config.yaml"

reward:
  type: 'cost' 
